### PR TITLE
Fix: cannot drag to medium presentation dentent

### PR DESCRIPTION
**Pull request by larryonoff**
Presentation detent interactive drag didn't work well when created without selection parameter. It often jumps back to large detent.

Fixed this by making selection an optional parameter.

### CODE REVIEW

**Comment by shaps80** [comment]
The back port APIs need to be drop-in replacements to ease migration later on.

I assume I made it non-optional on purpose, to match the official API (correct me if I'm wrong).

Therefore a different solution will be required. I think this is an easy solve without changing the API.

**Comment by larryonoff** [comment]
> The back port APIs need to be drop-in replacements to ease migration later on.
> 
> I assume I made it non-optional on purpose, to match the official API (correct me if I'm wrong).
> 
> Therefore a different solution will be required. I think this is an easy solve without changing the API.

I didn't change public signatures. I changed private signatures. So it's compatible with the official API.

**Comment by shaps80** [comment]
To be honest I was extremely busy with family stuff last week and had viewed this on my phone, clearly I missed that you'd only changed the internal implementation 👍

I'll re-open and run some tests to ensure if behaves as expected, otherwise (atm) I think you're right and this is a good change.

Apologies for the rushed review and thank you for raising the PR.

**Comment by shaps80** [comment]
Merged and now available in `1.6.3` – thanks again @larryonoff

**Pull request merged**
