### PR TITLE
Further fix on the task view modifier on iOS 14

### PR DESCRIPTION
**Pull request by hguandl**
This is a proceeding commit for #60. Sorry for my poor testing. I found the previous PR does not work on iOS 14. Specifically, `Just(value)` does not trigger the `onReceive` body on iOS 14. To workaround that, I get back to `onChange` for trigger, but use another publisher for the state update. This version has been tested on iOS 14.4, iOS 15.5, iOS 16.6 and macOS 13.5 (iOS 13 simulator is not supported on Xcode 14).

### CODE REVIEW

**Comment by shaps80** [comment]
I don't necessarily mind this change, however I know for a fact that I heavily tested the original implementation at the time, specifically for iOS 13, so I'm hesitant to change it without re-testing that it won't break that. Cause it 100% worked before given this was introduced specifically for iOS 13 initially.

If you can find a way to test this on iOS 13 and prove it works, I'll consider merging. Sorry for being a stickler but I don't want to break otherwise working code potentially 👍

**Comment by 0xfeedface1993** [comment]
@shaps80 Works on Xcode 14.2 iOS 13.7 simulator.

<video autoplay loop style="width:200px; height: auto; position:absolute; z-index: -1;">
  <source src="http://mobile.magicbean.top/Images/iOS%20SwiftUIBackports%20Test.mov" type="video/mov" />
  
</video>

simulator

**Comment by shaps80** [comment]
@0xfeedface1993 amazing thank you for verifying this and the quality of presenting it 💯

**Review by shaps80 — APPROVED** [review]
I deeply appreciate the patience and effort that went into ensuring this is the "right" fix. Thank you, I'll merge now and get this into the next release 👍

**Pull request merged**
